[BNBVISTA]
urls = ['https://connect.bbtheatres.com/WSVistaWebClient/OData.svc,3328be29639e4576995af178ba49bc9a']
prefix = 'BNBPEACH'
chain_id = 426
filter_houses = ''
search_on = 'chain'
method = 'vista'

[LOOKVISTA]
urls = ['https://connect.lookcinemas.com/wsvistawebclient/OData.svc,53b18b79f50b46d6a3c0465e247f50ea']
prefix = 'LOOK'
chain_id = 1331
filter_houses = ''
search_on = 'chain'
method = 'vista'

[LANDMARKVISTA]
urls = ['http://198.35.56.190/WSVistaWEbclient/OData.svc']
prefix = 'LANDMARKUS'
chain_id = 212
filter_houses = ''
search_on = 'chain'
method = 'vista'

[GOODRICHRTS]
urls = ['https://625520.formovietickets.com:2235/showtimes.xml',
        'https://418379.formovietickets.com:2235/showtimes.xml',
        'https://147783.formovietickets.com:2235/showtimes.xml',
        'https://286229.formovietickets.com:2235/showtimes.xml',
        'https://303419.formovietickets.com:2235/showtimes.xml',
        'https://316506.formovietickets.com:2235/showtimes.xml',
        'https://354283.formovietickets.com:2235/showtimes.xml',
        'https://359021.formovietickets.com:2235/showtimes.xml',
        'https://418379.formovietickets.com:2235/showtimes.xml',
        'https://558439.formovietickets.com:2235/showtimes.xml',
        'https://559503.formovietickets.com:2235/showtimes.xml',
        'https://625520.formovietickets.com:2235/showtimes.xml',
        'https://646644.formovietickets.com:2235/showtimes.xml',
        'https://661141.formovietickets.com:2235/showtimes.xml',
        'https://665046.formovietickets.com:2235/showtimes.xml',
        'https://737043.formovietickets.com:2235/showtimes.xml',
        'https://789597.formovietickets.com:2235/showtimes.xml',
        'https://794441.formovietickets.com:2235/showtimes.xml',
        'https://815376.formovietickets.com:2235/showtimes.xml',
        'https://851006.formovietickets.com:2235/showtimes.xml',
        'https://911039.formovietickets.com:2235/showtimes.xml',
        'https://945865.formovietickets.com:2235/showtimes.xml',
        'https://970420.formovietickets.com:2235/showtimes.xml',
        'https://199803.formovietickets.com:2235/showtimes.xml',
        'https://837818.formovietickets.com:2235/showtimes.xml',
        'https://747473.formovietickets.com:2235/showtimes.xml',
        'https://151668.formovietickets.com:2235/showtimes.xml']
prefix = 'GOODRICH'
chain_id = 115
filter_houses = ''
search_on = 'chain'
method = 'rts'

[DANBARRYRTS]
urls = ['https://825758.formovietickets.com:2235/showtimes.xml',
        'https://73182.formovietickets.com:2235/showtimes.xml',
        'https://59849.formovietickets.com:2235/showtimes.xml']
prefix = 'DANBARRY'
chain_id = 74
filter_houses = ''
search_on = 'chain'
method = 'rts'

[3BELOWRTS]
urls = ['https://505104.formovietickets.com:2235/showtimes.xml']
prefix = '3BELOW'
chain_id = 2495
filter_houses = ''
search_on = 'chain'
method = 'rts'

[ELVISRTS]
urls = ['https://84222.formovietickets.com:2235/showtimes.xml']
prefix = 'ELVIS'
chain_id = 661
filter_houses = '2939,782'
search_on = 'chain'
method = 'rts'

[ACXVISTA]
urls = ['https://ticketing.acxcinemas.com/WSVistaWebClient/OData.svc,018a3070fce54bea83a8dca8552f2cd2']
prefix = 'ACX'
chain_id = 79
filter_houses = '8557,2313,9187,8709'
search_on = 'chain'
method = 'vista'

[CPLUSAVISTA]
urls = ['https://ng-connec.cinepolisusa.com/WSVistaWebClient/OData.svc,QdfnlOzy9SSQsjrQKqBxkQVKWTf9cPR7']
prefix = 'CINEPOLISPEACH'
chain_id = 1199
filter_houses = ''
search_on = 'chain'
method = 'vista'

[CLOVERRTS]
urls = ['https://73508.formovietickets.com:2235/showtimes.xml']
prefix = 'CLOVER'
chain_id = 1381
filter_houses = ''
search_on = 'chain'
method = 'rts'

[PCCRTS]
urls = ['http://15655.formovietickets.com:2235/showtimes.xml','http://225.formovietickets.com:2235/showtimes.xml',
        'http://49.formovietickets.com:2235/showtimes.xml', 'http://66.formovietickets.com:2235/showtimes.xml',
        'http://77739.formovietickets.com:2235/showtimes.xml','http://52.formovietickets.com:2235/showtimes.xml',
        'http://24.formovietickets.com:2235/showtimes.xml', 'http://25.formovietickets.com:2235/showtimes.xml',
        'http://17872.formovietickets.com:2235/showtimes.xml','http://133.formovietickets.com:2235/showtimes.xml',
        'http://68.formovietickets.com:2235/showtimes.xml','http://82964.formovietickets.com:2235/showtimes.xml',
        'http://58098.formovietickets.com:2235/showtimes.xml','http://22759.formovietickets.com:2235/showtimes.xml',
        'http://26992.formovietickets.com:2235/showtimes.xml','http://7636.formovietickets.com:2235/showtimes.xml',
        'http://41395.formovietickets.com:2235/showtimes.xml','http://82390.formovietickets.com:2235/showtimes.xml',
        'http://29588.formovietickets.com:2235/showtimes.xml','http://23901.formovietickets.com:2235/showtimes.xml',
        'http://55340.formovietickets.com:2235/showtimes.xml','http://515794.formovietickets.com:2235/showtimes.xml',
        'http://794359.formovietickets.com:2235/showtimes.xml','http://813740.formovietickets.com:2235/showtimes.xml']
prefix = 'PREMIERE'
chain_id = 240
filter_houses = ''
search_on = 'chain'
method = 'rts'

[FLIXVISTA]
urls = ['https://ticketing.flixbrewhouse.com/WSVistaWebClient/OData.svc,1ba27c53964c48a1b3d8957189df2b03']
prefix = 'FLIX'
chain_id = 1212
filter_houses = ''
search_on = 'chain'
method = 'vista'

[FRIDLEYVISTA]
urls = ['https://vista.fridleytheatres.com/WSVistaWebClient/Odata.svc,7c54f8c94hhyt88oops989327dkfdmrnmleo']
prefix = 'FRIDLEY'
chain_id = 732
filter_houses = ''
search_on = 'chain'
method = 'vista'

[FRIDLEYRTS]
urls = ['http://19542.formovietickets.com:2235/showtimes.xml', 'http://69237.formovietickets.com:2235/showtimes.xml',
        'http://4249.formovietickets.com:2235/showtimes.xml', 'http://70903.formovietickets.com:2235/showtimes.xml',
        'http://32031.formovietickets.com:2235/showtimes.xml', 'http://77515.formovietickets.com:2235/showtimes.xml',
        'http://2322.formovietickets.com:2235/showtimes.xml', 'http://15484.formovietickets.com:2235/showtimes.xml',
        'http://64362.formovietickets.com:2235/showtimes.xml', 'http://2335.formovietickets.com:2235/showtimes.xml',
        'http://48102.formovietickets.com:2235/showtimes.xml', 'http://62867.formovietickets.com:2235/showtimes.xml',
        'http://44659.formovietickets.com:2235/showtimes.xml', 'http://66843.formovietickets.com:2235/showtimes.xml',
        'http://42398.formovietickets.com:2235/showtimes.xml', 'http://49158.formovietickets.com:2235/showtimes.xml',
        'http://18955.formovietickets.com:2235/showtimes.xml',  'http://26613.formovietickets.com:2235/showtimes.xml',
        'http://33387.formovietickets.com:2235/showtimes.xml', 'http://54171.formovietickets.com:2235/showtimes.xml']
prefix = 'FRIDLEY'
chain_id = 74
filter_houses = ''
search_on = 'chain'
method = 'rts'

[SHOWCASEVISTA]
urls = ['https://mobile.showcasecinemas.com/wsvistawebclient/odata.svc,c214a24bb9a2440b93d95a5fc357a6a0']
prefix = 'SHOWCASE'
chain_id = 20
filter_houses = ''
search_on = 'chain'
method = 'vista'

[PENNVISTA]
urls = ['https://tickets.penncinema.com/WSVistaWebClient/OData.svc,f7747d6f8e564fc99c014289e73ede1c']
prefix = 'PENNVISTA'
chain_id = 863
filter_houses = ''
search_on = 'chain'
method = 'vista'

[CITYBASEVISTA]
urls = ['https://webclient.citybasecinemas.com/WSVistaWebClient/OData.svc,c1aa7b38ae3a4cb8864a46d53663c4e9']
prefix = 'CITYBASEVISTA'
chain_id = [2468,1468]
filter_houses = ''
search_on = 'chain'
method = 'vista'

[CITYBASERTS]
urls = ['http://20389.formovietickets.com:2235/showtimes.xml']
prefix = 'CITYBASERTS'
chain_id = [2468,1468]
filter_houses = ''
search_on = 'chain'
method = 'rts'

[NPHVISTA]
urls = ['https://cinema.nphcinema.co.uk/WSVistaWebClient/Odata.svc,dkR6pYoUkZA35HvR']
prefix = 'NPHVISTA'
chain_id = 2301
filter_houses = ''
search_on = 'chain'
method = 'vista'

[CINEMASAVERRTS]
urls = ['https://45649.formovietickets.com:2235/showtimes.xml']
prefix = 'CINEMASAVER'
chain_id = 727
filter_houses = ''
search_on = 'chain'
method = 'rts'

[QUEENRTS]
urls = ['http://229640.formovietickets.com:2235/showtimes.xml']
prefix = 'QUEEN'
chain_id = 2506
filter_houses = ''
search_on = 'chain'
method = 'rts'

[LANDMARKPOSITIVE]
urls = ['https://restapi.landmarktheatres.com/api/movie/']
prefix = ''
chain_id = 212
filter_houses = ''
search_on = 'chain'
method = 'positive'

[METROVISTA]
urls = ['https://ticketing.metrotheatres.com/WSVistaWebClient/OData.svc,486A415E-289C-408F-9C9B-9BF9E7F92C68']
prefix = 'METROVISTA'
chain_id = 183
filter_houses = ''
search_on = 'chain'
method = 'vista'

[TOUCHSTARRTS]
urls = ['http://61139.formovietickets.com:2235/showtimes.xml', 'http://125.formovietickets.com:2235/showtimes.xml',
        'http://126.formovietickets.com:2235/showtimes.xml', 'http://135620.formovietickets.com:2245/showtimes.xml',
        'http://151590.formovietickets.com:2235/showtimes.xml']
prefix = 'TOUCHSTARRTS'
chain_id = 439
filter_houses = ''
search_on = 'chain'
method = 'rts'

[PRIMERTS]
urls = ['http://6357.formovietickets.com:2235/showtimes.xml', 'http://512138.formovietickets.com:2235/showtimes.xml']
prefix = 'PRIME'
chain_id = 2444
filter_houses = ''
search_on = 'chain'
method = 'rts'

[VINERTS]
urls = ['http://79655.formovietickets.com:2235/showtimes.xml']
prefix = 'VINE'
chain_id = 704
filter_houses = ''
search_on = 'chain'
method = 'rts'

[COBBLERTS]
urls = ['https://64785.formovietickets.com:2235/showtimes.xml']
prefix = 'COBBLE'
chain_id = 932
filter_houses = ''
search_on = 'chain'
method = 'rts'

[SUNRAYRTS]
urls = ['http://14438.formovietickets.com:2235/showtimes.xml']
prefix = 'GENRTS'
chain_id = 1510
filter_houses = ''
search_on = 'chain'
method = 'rts'

[FILMCARTS]
urls = ['http://75579.formovietickets.com:2235/showtimes.xml']
prefix = 'GENRTS'
chain_id = 1165
filter_houses = ''
search_on = 'chain'
method = 'rts'

[CARTS]
urls = ['https://80.formovietickets.com:2235/showtimes.xml', 'https://327904.formovietickets.com:2235/showtimes.xml']
prefix = 'GENRTS'
chain_id = 1165
filter_houses = ''
search_on = 'chain'
method = 'rts'

[HOMETOWNRTS]
urls = ['http://64136.formovietickets.com:2235/showtimes.xml','http://33625.formovietickets.com:2235/showtimes.xml',
        'http://9837.formovietickets.com:2235/showtimes.xml', 'http://926632.formovietickets.com:2235/showtimes.xml']
prefix = 'HOMETOWN'
chain_id = 1144
filter_houses = '5961'
search_on = 'chain'
method = 'rts'

[RIALTORTS]
urls = ['http://442088.formovietickets.com:2235/showtimes.xml']
prefix = 'FRMRTS'
chain_id = 2541
filter_houses = ''
search_on = 'chain'
method = 'rts'

[EPICPOSITIVE]
urls = ['https://restapi.epictheatres.com/api/movie/']
prefix = 'EPIC'
chain_id = 711
filter_houses = ''
search_on = 'chain'
method = 'positive'

[PARAMOUNTRTS]
urls = ['http://21863.formovietickets.com:2235/showtimes.xml']
prefix = 'PARAMOUNTRTS'
chain_id = 207
filter_houses = ''
search_on = 'chain'
method = 'rts'

[VISIONMAXRTS]
urls = ['http://33964.formovietickets.com:2235/showtimes.xml']
prefix = 'GENRTS'
chain_id = 1137
filter_houses = ''
search_on = 'chain'
method = 'rts'

[FANDANGO]
urls = ['F:\fandango']
prefix = ''
chain_id = ''
filter_houses = ''
search_on = 'fandango'
method = 'fandango'

[EVERYMANVISTA]
urls = ['https://digital-api.everymancinema.com/odata.svc,QaGZqrJp9P9nmbE,webhost-everyman-theboxofficecompany']
prefix = 'EVERYMAN'
chain_id = 1077
filter_houses = ''
search_on = 'chain'
method = 'mxc'

[CELEBRITYRTS]
urls = ['https://33015.formovietickets.com:2235/showtimes.xml', 'http://22792.formovietickets.com:2235/showtimes.xml',
        'http://62050.formovietickets.com:2235/showtimes.xml']
prefix = 'CELEBRITY'
chain_id = 729
filter_houses = ''
search_on = 'chain'
method = 'rts'

[HARPERRTS]
urls = ['http://82003.formovietickets.com:2235/showtimes.xml']
prefix = 'HARPER'
chain_id = 2416
filter_houses = ''
search_on = 'chain'
method = 'rts'

[CARVERRTS]
urls = ['http://81785.formovietickets.com:2235/showtimes.xml']
prefix = 'CARVER'
chain_id = 2028
filter_houses = ''
search_on = 'chain'
method = 'rts'

[ABINGDONRTS]
urls = ['http://41110.formovietickets.com:2235/showtimes.xml']
prefix = 'ABINGDON'
chain_id = 780
filter_houses = ''
search_on = 'chain'
method = 'rts'

[PARKPLAZARTS]
urls = ['http://10062.formovietickets.com:2235/showtimes.xml']
prefix = 'PARKPLAZA'
chain_id = 1321
filter_houses = ''
search_on = 'chain'
method = 'rts'

[COYOTERTS]
urls = ['http://310377.formovietickets.com:2235/showtimes.xml']
prefix = 'COYOTE'
chain_id = 2297
filter_houses = ''
search_on = 'chain'
method = 'rts'

[BOULEVARDRTS]
urls = ['http://863314.formovietickets.com:2235/showtimes.xml']
prefix = 'BOULEVARD'
chain_id = 2549
filter_houses = ''
search_on = 'chain'
method = 'rts'

[WARSAWRTS]
urls = ['https://62720.formovietickets.com:2235/showtimes.xml', 'https://81825.formovietickets.com:2235/showtimes.xml']
prefix = 'FRMRTS'
chain_id = 1588
filter_houses = ''
search_on = 'chain'
method = 'rts'

[GROSSRTS]
urls = ['https://59311.formovietickets.com:2235/showtimes.xml']
prefix = 'GROSS'
chain_id = 643
filter_houses = ''
search_on = 'chain'
method = 'rts'

[KEWRTS]
urls = ['https://64785.formovietickets.com:2235/showtimes.xml', 'https://29595.formovietickets.com:2235/showtimes.xml',
        'https://43045.formovietickets.com:2235/showtimes.xml']
prefix = 'KEW'
chain_id = 628
filter_houses = ''
search_on = 'chain'
method = 'rts'

[CROWLEYRTS]
urls = ['https://43449.formovietickets.com:2235/showtimes.xml']
prefix = 'CROWLEY'
chain_id = 1228
filter_houses = ''
search_on = 'chain'
method = 'rts'

[SANCTUARYRTS]
urls = ['https://920994.formovietickets.com:2235/showtimes.xml']
prefix = 'SANCTUARY'
chain_id = ''
filter_houses = ''
search_on = 'chain'
method = 'rts'

[SUNRTS]
urls = ['https://40102.formovietickets.com:2235/showtimes.xml']
prefix = 'SUNRTS'
chain_id = 2588
filter_houses = ''
search_on = 'chain'
method = 'rts'

[AMERICARTS]
urls = ['https://70351.formovietickets.com:2235/showtimes.xml', 'https://74999.formovietickets.com:2235/showtimes.xml',
        'https://501628.formovietickets.com:2235/showtimes.xml']
prefix = 'SUNRTS'
chain_id = 2588
filter_houses = ''
search_on = 'chain'
method = 'rts'

[SHOWBIZVISTA]
urls = ['https://api.showbizcinemas.com/wsvistawebclient/Odata.svc,3812731d294845f184e94fd8f4fc7645']
prefix = 'SHOWBIZVISTA'
chain_id = 946
filter_houses = ''
search_on = 'chain'
method = 'vista'

[EVOVISTA]
urls = ['http://vista.evo-entertainment.com/WSVistaWebClient/OData.svc,15dd5453e44a409783e61f16ebcdcce5']
prefix = 'EVOVISTA'
chain_id = 2152
filter_houses = ''
search_on = 'chain'
method = 'vista'

[STARLIGHTVISTA]
urls = ['https://ticketing.starlightcinemas.com/wsvistawebclient/OData.svc,8c4d8719344c4f86a7a72c4e0db86989']
prefix = 'STARLIGHTVISTA'
chain_id = 1605
filter_houses = ''
search_on = 'chain'
method = 'vista'

[MJRVISTA]
urls = ['https://connect.mjrtheatres.com/WSVistaWebClient/OData.svc,403e83ce-7d76-4889-8616-75e434931a3e']
prefix = 'MJRVISTA'
chain_id = 607
filter_houses = ''
search_on = 'chain'
method = 'vista'

[CINEMAXXVISTA]
urls = ['https://vista.biografenvue.dk/WSVistaWebClient/OData.svc,a4ba1eed53ef4fbfa377fccfb29dff92']
prefix = 'CINEMAXX'
chain_id = 1996
filter_houses = ''
search_on = 'chain'
method = 'vista'

[ELKADERRTS]
urls = ['https://3831.formovietickets.com:2235/showtimes.xml', 'https://74232.formovietickets.com:2235/showtimes.xml',
        'https://17666.formovietickets.com:2235/showtimes.xml']
prefix = 'FRMRTS'
chain_id = 1512
filter_houses = ''
search_on = 'chain'
method = 'rts'

[CABBRTS]
urls = ['https://894817.formovietickets.com:2235/showtimes.xml', 'https://793806.formovietickets.com:2235/showtimes.xml']
prefix = 'FRMRTS'
chain_id = 2555
filter_houses = ''
search_on = 'chain'
method = 'rts'

[SPOTLIGHTRTS]
urls = ['https://694207.formovietickets.com:2235/showtimes.xml', 'https://62720.formovietickets.com:2235/showtimes.xml',
        'https://81825.formovietickets.com:2235/showtimes.xml', 'https://371349.formovietickets.com:2235/showtimes.xml']
prefix = 'FRMRTS'
chain_id = 2555
filter_houses = ''
search_on = 'chain'
method = 'rts'

[ONYXRTS]
urls = ['https://756038.formovietickets.com:2235/showtimes.xml']
prefix = 'FRMRTS'
chain_id = 2528
filter_houses = ''
search_on = 'chain'
method = 'rts'

[SHOWCASEUKVISTA]
urls = ['https://webconnect.uatwmpnatl.co.uk/WSVistaWebClient/OData.svc,IBAHkRr30SQXhUgqXHyPZcMGQaF55mur']
prefix = 'SHOWCASEUK'
chain_id = 577
filter_houses = ''
search_on = 'chain'
method = 'vista'

[SCUKTEMPVISTA]
urls = ['https://webconnect.showcasecinemas.co.uk/WSVistaWebClient/OData.svc,a719be59f38b4adeb7113d225e5b08d2']
prefix = 'SHOWCASE'
chain_id = 577
filter_houses = ''
search_on = 'chain'
method = 'vista'

[EVERYMANVISTABACK]
urls = ['https://reservations.everymancinema.com/WSVistaWebClient/odata.svc,29127l315u83340fev033Us477Cnr2nq0D624qJR5269Q44C0nn1778TA87v']
prefix = 'EVERYMAN'
chain_id = 1077
filter_houses = ''
search_on = 'chain'
method = 'vista'

[EVERYMANTEST]
urls = ['https://digital-api.sandbox.everymancinema.com/odata.svc,vnYQW9b4wFdNKiu,webhost-everyman-theboxofficecompany']
prefix = 'EVERYMAN'
chain_id = 1077
filter_houses = ''
search_on = 'chain'
method = 'mxc'

[STATERTS]
urls = ['https://61565.formovietickets.com:2235/showtimes.xml', 'https://162.formovietickets.com:2235/showtimes.xml',
        'https://24552.formovietickets.com:2235/showtimes.xml', 'https://80756.formovietickets.com:2235/showtimes.xml',
        'https://8342.formovietickets.com:2235/showtimes.xml', 'https://33.formovietickets.com:2235/showtimes.xml']
prefix = 'FRMRTS,GENRTS'
chain_id = 144
filter_houses = ''
search_on = 'chain'
method = 'rts'

[CINELOUNGERTS]
urls = ['https://746166.formovietickets.com:2235/showtimes.xml']
prefix = 'CINELOUNGERTS'
chain_id = 1325
filter_houses = ''
search_on = 'chain'
method = 'rts'

[PORTAGERTS]
urls = ['https://33810.formovietickets.com:2235/showtimes.xml']
prefix = 'PORTAGERTS'
chain_id = 2090
filter_houses = ''
search_on = 'chain'
method = 'rts'

[EDMONDRTS]
urls = ['https://664115.formovietickets.com:2235/showtimes.xml']
prefix = 'EDMONDRTS'
chain_id = 2598
filter_houses = ''
search_on = 'chain'
method = 'rts'
