[BNBVISTA]
urls = ['https://connect.bbtheatres.com/WSVistaWebClient/OData.svc']
prefix = 'BNBPEACH'
chain_id = 426
filter_houses = ''
search_on = 'chain'
method = 'vista'

[LOOKVISTA]
urls = ['https://connect.lookcinemas.com/wsvistawebclient/OData.svc,53b18b79f50b46d6a3c0465e247f50ea']
prefix = 'LOOK'
chain_id = 1331
filter_houses = ''
search_on = 'chain'
method = 'vista'

[LANDMARKVISTA]
urls = ['http://198.35.56.190/WSVistaWEbclient/OData.svc']
prefix = 'LANDMARKUS'
chain_id = 212
filter_houses = ''
search_on = 'chain'
method = 'vista'